export enum TypeActivity {
  CREATESCHEDULE = "CREATESCHEDULE",
  CONFIRMSCHEDULE = "CONFIRMSCHEDULE",
  CREATEACCOUNT = "CREATEACCOUNT",
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  CANCELASCHEDULE = "CANCELASCHEDULE",
  UPDATEEMAIL = "UPDATEEMAIL",
  UPDATEADRESS = "UPDATEADRESS",
}
